# Generated by Django 2.0.10 on 2019-01-29 22:02

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gwas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('analysis', models.CharField(help_text='A human-label describing the analysis performed, eg DIAGRAM Height GWAS', max_length=100)),
                ('build', models.CharField(choices=[('GRCh37', 'GRCh37'), ('GRCh38', 'GRCh38')], max_length=10)),
                ('imputed', models.CharField(blank=True, max_length=25)),
                ('is_log_pvalue', models.BooleanField(default=True)),
                ('pipeline_complete', models.DateTimeField(null=True)),
                ('file_location', models.FileField(upload_to='')),
                ('file_sha256', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RegionView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('label', models.CharField(max_length=100)),
                ('chrom', models.CharField(max_length=5)),
                ('start', models.PositiveIntegerField()),
                ('end', models.PositiveIntegerField()),
                ('options', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('gwas', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='gwas.Gwas')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='gwas',
            name='top_hit_view',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gwas.RegionView'),
        ),
        migrations.AddField(
            model_name='gwas',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
