# Generated by Django 2.0.10 on 2019-02-01 18:39

from django.db import migrations, models
import locuszoom_plotting_service.gwas.models
import locuszoom_plotting_service.gwas.util


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwas',
            name='pipeline_path',
            field=models.CharField(default=locuszoom_plotting_service.gwas.models._pipeline_folder, help_text='Internal use only: where to store the group of files generated by the upload pipeline?', max_length=32),
        ),
        migrations.RenameField(
            model_name='gwas',
            old_name='file_location',
            new_name='raw_gwas_file',
        ),
        migrations.AlterField(
            model_name='gwas',
            name='analysis',
            field=models.CharField(help_text='A human-readable label describing the analysis performed, eg DIAGRAM Height GWAS', max_length=100),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='imputed',
            field=models.CharField(blank=True, help_text='If your data was imputed, please specify the reference panel used', max_length=25),
        ),
    ]
