# Generated by Django 2.0.10 on 2019-02-20 17:59

from django.db import migrations, models
import locuszoom_plotting_service.gwas.models
import locuszoom_plotting_service.gwas.util


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0002_auto_20190201_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwas',
            name='analysis',
            field=models.CharField(help_text='A human-readable description, eg DIAGRAM Height GWAS', max_length=100),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='imputed',
            field=models.CharField(blank=True, choices=[('CAAPA', 'CAAPA - African American Panel'), ('1000G', '1000 Genomes'), ('hapmap2', 'HapMap 2'), ('hrc1', 'HRC r1 2015'), ('hrc.r1.1.2016', 'HRC r1.1 2016'), ('1000G-phase1', '1000G Phase 1 v3 Shapeit2 (no singletons)'), ('1000G-phase3', '1000G Phase 3 v5'), ('other', 'Other (unspecified)')], help_text='If your data was imputed, please specify the reference panel used', max_length=25),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='pipeline_path',
            field=models.CharField(default=locuszoom_plotting_service.gwas.models._pipeline_folder, help_text='Internal use only: path to folder of ingested data', max_length=32),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='raw_gwas_file',
            field=models.FileField(upload_to=locuszoom_plotting_service.gwas.util.get_gwas_raw_fn),
        ),
    ]
