# Generated by Django 2.0.13 on 2019-08-26 18:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0002_auto_20190723_1903'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewLink',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('code', models.CharField(help_text='A unique code that is tied to one specific study', max_length=32, primary_key=True, serialize=False)),
                ('label', models.CharField(blank=True, default='', help_text='A human-readable description (eg "Shared with journal reviewers")', max_length=100)),
                ('gwas', models.ForeignKey(help_text='The analysis to be shared', on_delete=django.db.models.deletion.CASCADE, to='gwas.AnalysisInfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
