# Generated by Django 2.0.13 on 2019-08-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0003_viewlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinfo',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
