# Generated by Django 2.0.10 on 2019-02-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0004_auto_20190222_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gwas',
            old_name='pipeline_complete',
            new_name='ingest_complete'
        ),
        migrations.AddField(
            model_name='gwas',
            name='ingest_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'FAILED'), (2, 'SUCCESS')], default=0, help_text='Track progress of data ingestion'),
        ),
        migrations.AddField(
            model_name='gwas',
            name='n_cases',
            field=models.PositiveIntegerField(blank=True, help_text='Number of phenotype cases in sample', null=True),
        ),
        migrations.AddField(
            model_name='gwas',
            name='n_controls',
            field=models.PositiveIntegerField(blank=True, help_text='Number of phenotype controls in sample', null=True),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='file_sha256',
            field=models.CharField(help_text='The hash of the original, raw uploaded file', max_length=64),
        ),
    ]
