# Generated by Django 2.0.13 on 2019-09-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0004_analysisinfo_is_removed'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisinfo',
            name='study_name',
            field=models.CharField(blank=True, help_text='The name of the study or dataset that produced this GWAS (DIAGRAM, GLGC, etc)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='analysisinfo',
            name='label',
            field=models.CharField(help_text='A human-readable description, eg Height GWAS', max_length=100),
        ),
    ]
