# Generated by Django 2.0.10 on 2019-02-25 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0005_auto_20190225_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwas',
            name='ingest_complete',
            field=models.DateTimeField(help_text='When the ingestion pipeline completed (success or failure)', null=True),
        ),
    ]
