# Generated by Django 2.0.13 on 2020-02-14 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0005_auto_20190929_0344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisinfo',
            options={'verbose_name_plural': 'GWAS Analysis Metadata'},
        ),
    ]
