# Generated by Django 2.0.13 on 2019-04-15 20:09

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import locuszoom_plotting_service.gwas.util


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0006_auto_20190225_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gwas',
            name='is_log_pvalue',
        ),
        migrations.AddField(
            model_name='gwas',
            name='parser_options',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, help_text='Parser options (zorp-compatible parser kwarg names)'),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='raw_gwas_file',
            field=models.FileField(help_text='The GWAS data to be uploaded. May be text-based, or (b)gzip compressed', upload_to=locuszoom_plotting_service.gwas.util.get_gwas_raw_fn, verbose_name='GWAS file'),
        ),
    ]
