# Generated by Django 2.0.13 on 2019-04-23 21:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0007_auto_20190415_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='gwas',
            name='pmid',
            field=models.CharField(blank=True, help_text='The PubMed ID associated with a published GWAS', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='regionview',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, help_text='Additional arbitrary params associated with the page- URL query params. (eg plot features or options)', null=True),
        ),
    ]
