# Generated by Django 2.0.13 on 2019-04-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0008_auto_20190423_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regionview',
            name='gwas',
        ),
    ]
