# Generated by Django 2.0.13 on 2019-04-25 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0009_remove_regionview_gwas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwas',
            name='pmid',
            field=models.CharField(blank=True, help_text='The PubMed ID associated with a published GWAS', max_length=20, null=True),
        ),
    ]
