# Generated by Django 2.0.13 on 2019-04-25 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0010_auto_20190425_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gwas',
            name='file_sha256',
            field=models.BinaryField(help_text='The hash of the original, raw uploaded file', max_length=32),
        ),
        migrations.AlterField(
            model_name='gwas',
            name='top_hit_view',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gwas.RegionView'),
        ),
    ]
