# Generated by Django 2.0.13 on 2019-07-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gwas', '0011_auto_20190425_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='OntologyTerm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='The unique identifier used by the nomenclature system', max_length=20, unique=True)),
                ('label', models.TextField(help_text='A human-readable description of the code')),
                ('scheme', models.SmallIntegerField(choices=[(1, 'SNOMED CT')], help_text='The classification scheme (SNOMED, ICDx, etc)')),
            ],
        ),
        migrations.AlterField(
            model_name='gwas',
            name='pmid',
            field=models.CharField(blank=True, help_text='The PubMed ID associated with a published GWAS', max_length=20, null=True, verbose_name='PMID'),
        ),
        migrations.AlterUniqueTogether(
            name='ontologyterm',
            unique_together={('code', 'scheme')},
        ),
    ]
