#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ -n "${CELERY_WORKERS}" ]; then
  CONCURRENCY="--concurrency ${CELERY_WORKERS}"
else
  CONCURRENCY=""
fi

celery -A locuszoom_plotting_service.taskapp worker -l INFO ${CONCURRENCY}
