#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py collectstatic --noinput
# Gunicorn needs to handle long uploads: use async workers and longer timeouts
/usr/local/bin/gunicorn config.wsgi --bind 0.0.0.0:5000 --chdir=/app -t 60 --worker-class gevent
